// "nombres": "pruebaas",
// "apellidos": "kjhvcxzas",
// "contrasena":"123456",
// "tipo_doc": "T.I",
// "n_doc": "nbvcsdasd",
// "telefono": "1234567890",
// "correo_inst": "ajwfmlsfja@soysena.edu.co",
// "correo_pers": "lhkgjhfgfds@soysena.edu.co",
// "nacimiento": "2023-09-16",
// "rol": "64ecc37d38bcaef6a8278538",
// "ficha": "64f4b785d7a4f18f059f2e98",
// "direccion": "sdfghj",
// "rh": "B+",
// "genero": "Femenino",
// "eps": "64ff1a5599702a8b78ddcd5a",
// "pps": true,
// "activacion": false

let datosRegistro = {
	nombres: '',
	apellidos: '',
	tipo_doc: '',
	n_doc: '',
	telefono: '',
	correo_inst: '',
	correo_pers: '',
	nacimiento: '',
	ficha: '',
	rol: '',
	direccion: '',
	rh: '',
	genero: '',
	eps: '',
	pps: false,
	activacion: true,
}

export { datosRegistro }
